<a href="https://colab.research.google.com/github/Xueyi-Wang/CNN-Action-Recognition/blob/master/fall_detection_using_SVM_by_largeer_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing packages

In [12]:
import os
import csv
import cv2
import re
import math
print(cv2.__version__)
from pathlib import Path

import keras
import torch
from keras.models import Sequential

from keras.preprocessing import image
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import VGG16
from keras.models import Model

from keras.layers import Dense, InputLayer, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, GlobalMaxPooling2D
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from torchvision import datasets, models
import torch.nn as nn
import os, glob

from glob import glob
from tqdm import tqdm

import numpy as np

from numpy import asarray
from numpy import save


# load pretrained model



selectedCNN = 'VGG'

# listCNNs = ['VGG','ResNet','Xception']

4.1.2


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# Prepare the model and saving the FC layer from vgg16

In [14]:
# revised code
# path to folder
files_path = '/content/drive/My Drive/fall_detection_100/fall_detection_large_dataset_images/'
falls_image_path = '/content/drive/My Drive/fall_detection_100/fall_detection_large_dataset_images/falls/'
nonfalls_image_path = '/content/drive/My Drive/fall_detection_100/fall_detection_large_dataset_images/nonfalls/'
features_path = '/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/'
# nonfalls_path = '/content/drive/My Drive/fall_detection_100/nonfalls/'

# --------------------------------------------------------------------------------------------
model = models.vgg16(pretrained=True)
### PREPARE MODEL : 
if selectedCNN == 'VGG': #  SELECT VGG NETWORK 
  model = VGG16()#weights='imagenet', include_top=False)
elif selectedCNN == 'ResNet': #  SELECT ResNet NETWORK 
  model = models.resnet18(pretrained=True)
elif selectedCNN == 'Xception': #  SELECT Xception NETWORK 
  model = models.XXXX(pretrained=True)

# remove the output layer (softmax) - thus, the last layer will be the fully-connected
model.layers.pop()
model = Model(inputs=model.inputs, outputs=model.layers[-1].output)

# here we check how many classes we have: 2 classes : fall vs non fall
list_classes = os.listdir(files_path)
print ("list_name = ",list_classes) # this should print fall and nonfall

train_x = []
train_y = []

for class_name in list_classes:
  # here we are inside on the classes
  # print('class name ',class_name)

  # go through the folders of that class
  list_events_class = os.listdir(files_path + class_name)


  
  for folder in list_events_class:

    #label the devent
    if class_name == "falls":
      train_y.append(1)
    else:
      train_y.append(0)
    print("name of folder ", folder)
    
    # # find list of images within folder that end with jpg 
    # list_images = glob(files_path + class_name + '/' + folder+ '/' + '*.jpg')
    # # list_features=[]
    # # list_features= np.array([]) 
    # list_features = np.array([], dtype=np.int64).reshape(0,4096)

    # for image_name in list_images:

    #   # LOAD IMAGE (img = cv2.imread(files_path + class_name + '/' + folder+ '/' + image_name))
    #   print ('image_name ', image_name)
    #   img = load_img(image_name, target_size=(224,224))
    #   # convert the image pixels to a numpy array
    #   img = img_to_array(img)
    #   # reshape data for the model
    #   img = img.reshape((1, img.shape[0], img.shape[1], img.shape[2]))
    #   # prepare the image for the VGG model
    #   img = preprocess_input(img)

    #   # print('image shape ',img.shape)
    #   features = model.predict(img)
    #   # if class_name == "falls":
    #   #   train_y.append(1)
    #   # else:
    #   #   train_y.append(0)

    #   # convert the probabilities to class labels
    #   # print('features shape ',features.shape) # to check, it should be equal to dimensions of FC of the VGG
    #   # retrieve the most likely result, e.g. highest probability
    #   # print("features")
    #   # print("type of feautres = ",type(features))
    #   # print("feature shape before cancatenation =", np.shape(features))
    #   # print("shape of list_features = ", list_features)

    #   list_features = np.concatenate((list_features,features), axis = 0)

     
    #   # print("feature shape after concatenation", np.shape(features))

      
    #   #list_features.append(features)
    # list_features = list_features.reshape(1,40960)
    # # print("feature shape after concatenation of whole event", np.shape(list_features))
    
      
    # np.save(features_path + class_name + '_' + folder +'_features' + selectedCNN,list_features)
np.save(files_path +'train_y.npy', train_y)
    # print('Length list features', len(list_features))  
    

553467904/553467096 [==============================] - 40s 0us/step
list_name =  ['falls', 'nonfalls']
name of folder  fall0
name of folder  fall1
name of folder  fall2
name of folder  fall3
name of folder  fall4
name of folder  fall5
name of folder  fall6
name of folder  fall7
name of folder  fall8
name of folder  fall9
name of folder  fall10
name of folder  fall11
name of folder  fall12
name of folder  fall13
name of folder  fall14
name of folder  fall15
name of folder  fall16
name of folder  fall17
name of folder  fall18
name of folder  fall19
name of folder  fall20
name of folder  fall21
name of folder  fall22
name of folder  fall23
name of folder  fall24
name of folder  fall25
name of folder  fall26
name of folder  fall27
name of folder  fall28
name of folder  fall29
name of folder  fall30
name of folder  fall31
name of folder  fall32
name of folder  fall33
name of folder  fall34
name of folder  fall35
name of folder  fall36
name of folder  fall37
name of folder  fall38
name of fo

In [15]:
np.load(files_path +'train_y.npy')
print(train_y)
print("train_y = ",len(train_y))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
train_y =  236


In [0]:
file_path = '/content/drive/My Drive/fall_detection_100/fall_detection_large_dataset_images/'
falls_image_path = '/content/drive/My Drive/fall_detection_100/fall_detection_large_dataset_images/falls/'
nonfalls_image_path = '/content/drive/My Drive/fall_detection_100/fall_detection_large_dataset_images/nonfalls/'
features_path = '/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/'
# nonfalls_path = '/content/drive/My Drive/fall_detection_100/nonfalls/'
for features in os.listdir(features_path):
  print(features)
  print(features_path + features)
  train_features = np.load(features_path + features)
  print('train_features = ', train_features)
  print("len of features", train_features.shape)

falls_fall0_featuresVGG.npy
/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/falls_fall0_featuresVGG.npy
train_features =  [[0.         0.         0.         ... 0.         1.1554575  1.23103273]]
len of features (1, 40960)
falls_fall1_featuresVGG.npy
/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/falls_fall1_featuresVGG.npy
train_features =  [[0.34197319 0.28670388 0.         ... 0.26785034 0.         1.57339966]]
len of features (1, 40960)
falls_fall2_featuresVGG.npy
/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/falls_fall2_featuresVGG.npy
train_features =  [[0.18667799 2.32713985 0.16542494 ... 0.         0.         1.13389969]]
len of features (1, 40960)
falls_fall3_featuresVGG.npy
/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/falls_fall3_featuresVGG.npy
train_features =  [[0.         0.         0.         ... 0.         0.         2.10861611]]
len of features (1, 40960)
falls_fall4_feat

In [17]:
# # concatenate all features
# train_feature = []
# train_x = []
# features_path = '/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/'
# for features in os.listdir(features_path):
#   print("features", features)
#   train_feature = np.load(features_path + features)
#   train_feature = np.concatenate(train_feature, axis = 1)
#   # print("train_feature",train_feature.shape)
#   train_x.append(train_feature)
#   print("train_x = ", train_x)
#   # print("train_x shape = ", train_x.shape)
# train_x = np.stack(train_x, axis=1)


train_feature = []
train_x = []
features_path = '/content/drive/My Drive/fall_detection_100/feature_path_larger_dataset/'
for features in os.listdir(features_path):
  print(features)
  train_feature = np.load(features_path + features)
  # train_feature = np.concatenate(train_feature, axis = 1)
  print(train_feature.shape)
  train_x.append(train_feature)
  # print("train_x = ", train_x)
  # print("train_x shape = ", train_x.shape)
train_x = np.vstack(train_x)
print("shape of train_x",train_x.shape)


falls_fall0_featuresVGG.npy
(1, 40960)
falls_fall1_featuresVGG.npy
(1, 40960)
falls_fall2_featuresVGG.npy
(1, 40960)
falls_fall3_featuresVGG.npy
(1, 40960)
falls_fall4_featuresVGG.npy
(1, 40960)
falls_fall5_featuresVGG.npy
(1, 40960)
falls_fall6_featuresVGG.npy
(1, 40960)
falls_fall7_featuresVGG.npy
(1, 40960)
falls_fall8_featuresVGG.npy
(1, 40960)
falls_fall9_featuresVGG.npy
(1, 40960)
falls_fall10_featuresVGG.npy
(1, 40960)
falls_fall11_featuresVGG.npy
(1, 40960)
falls_fall12_featuresVGG.npy
(1, 40960)
falls_fall13_featuresVGG.npy
(1, 40960)
falls_fall14_featuresVGG.npy
(1, 40960)
falls_fall15_featuresVGG.npy
(1, 40960)
falls_fall16_featuresVGG.npy
(1, 40960)
falls_fall17_featuresVGG.npy
(1, 40960)
falls_fall18_featuresVGG.npy
(1, 40960)
falls_fall19_featuresVGG.npy
(1, 40960)
falls_fall20_featuresVGG.npy
(1, 40960)
falls_fall21_featuresVGG.npy
(1, 40960)
falls_fall22_featuresVGG.npy
(1, 40960)
falls_fall23_featuresVGG.npy
(1, 40960)
falls_fall24_featuresVGG.npy
(1, 40960)
falls_fall

In [32]:
print(train_x)
print("train_x",train_x.shape)
print(train_y)
print("length train_y = ",len(train_y))

[[0.         0.         0.         ... 0.         1.1554575  1.23103273]
 [0.34197319 0.28670388 0.         ... 0.26785034 0.         1.57339966]
 [0.18667799 2.32713985 0.16542494 ... 0.         0.         1.13389969]
 ...
 [0.         0.         1.98470414 ... 0.         0.         0.        ]
 [0.         0.         1.87504411 ... 0.         0.         0.        ]
 [1.74099219 0.         1.16259408 ... 0.         0.         0.        ]]
train_x (236, 40960)
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(train_x, train_y, test_size=0.33, random_state=42)

In [37]:
print("X_train",X_train)
print("X_train.shape",X_train.shape)
print("Y_train", Y_train)
print("Y_train.shape", len(Y_train))
print("X_test", X_test)
print("X_test.shape", X_test.shape)
print("Y_test", Y_test)
print("Y_test.shape",len(Y_test))

X_train [[0.         0.         0.         ... 0.         0.         0.27750215]
 [0.         2.27505994 0.         ... 0.         0.48448265 0.        ]
 [2.87180948 0.         1.76608372 ... 0.         0.         3.62972927]
 ...
 [2.55039835 0.         0.         ... 0.         0.         0.        ]
 [1.15101099 0.09755006 2.32013392 ... 0.         0.         3.34273314]
 [0.         0.         0.         ... 1.09639883 0.         0.68824446]]
X_train.shape (158, 40960)
Y_train [1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1]
Y_train.shape 158
X_test [[0.         

# Train with SVM classifier

In [0]:
from sklearn.svm import SVC
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# First method to evaluate the scores

In [0]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, Y_train)

In [44]:
clf.score(X_test, Y_test)

1.0

# second method to evaluate the score

In [0]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train, Y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='auto', kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [0]:
Y_predict = clf.predict(X_test)
print(Y_predict)

[1 0 0 1 1 1 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 0 0
 1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1
 1 1 1 0]


In [0]:
print(Y_test)

[1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]


In [0]:
accuracy_score(Y_test, Y_predict)

0.9230769230769231

In [0]:
print(classification_report(Y_test, Y_predict))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91        36
           1       0.88      1.00      0.93        42

    accuracy                           0.92        78
   macro avg       0.94      0.92      0.92        78
weighted avg       0.93      0.92      0.92        78



# Computing 10-folds cross validation

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn import svm

In [0]:
clf2 = svm.SVC(kernel = 'linear', C = 1)

In [0]:
scores = cross_val_score(clf2, train_x, train_y, cv=10)

In [62]:
scores

array([1.        , 1.        , 0.95833333, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [63]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 1.00 (+/- 0.02)
